import { GenreID } from './types';

// Map TMDb Genre IDs to human readable strings
export const GENRE_MAP: Record<number, string> = {
  [GenreID.ActionAdventure]: 'Action & Adventure',
  [GenreID.Animation]: 'Animation',
  [GenreID.Comedy]: 'Comedy',
  [GenreID.Crime]: 'Crime',
  [GenreID.Documentary]: 'Documentary',
  [GenreID.Drama]: 'Drama',
  [GenreID.Family]: 'Family',
  [GenreID.Kids]: 'Kids',
  [GenreID.Mystery]: 'Mystery',
  [GenreID.News]: 'News',
  [GenreID.Reality]: 'Reality',
  [GenreID.SciFiFantasy]: 'Sci-Fi & Fantasy',
  [GenreID.Soap]: 'Soap Opera',
  [GenreID.Talk]: 'Talk',
  [GenreID.WarPolitics]: 'War & Politics',
  [GenreID.Western]: 'Western',
};

// Filter Config
export const FILTER_CONFIG = {
  MIN_VOTES: 100,
  MIN_RATING: 5.0,
  SORT_BY: 'first_air_date.desc',
};

// Sort Options
export const SORT_OPTIONS = [
  { value: 'first_air_date.desc', label: 'Newest' },
  { value: 'first_air_date.asc', label: 'Oldest' },
  { value: 'vote_average.desc', label: 'Top Rated' },
  { value: 'vote_count.desc', label: 'Most Voted' },
  { value: 'popularity.desc', label: 'Popularity' },
];

export const WATCHLIST_SORT_OPTIONS = [
  { value: 'addedAt.desc', label: 'Recently Added' },
  { value: 'addedAt.asc', label: 'Earliest Added' },
  { value: 'bingeHours.asc', label: 'Shortest Binge' },
  { value: 'bingeHours.desc', label: 'Longest Binge' },
  { value: 'first_air_date.desc', label: 'Newest' },
  { value: 'first_air_date.asc', label: 'Oldest' },
  { value: 'vote_average.desc', label: 'Top Rated' },
  { value: 'vote_count.desc', label: 'Most Rated' },
  { value: 'popularity.desc', label: 'Popularity' },
];

// Full list of TMDb TV Genres
export const POPULAR_GENRES = [
  { id: GenreID.ActionAdventure, name: 'Action & Adventure' },
  { id: GenreID.Animation, name: 'Animation' },
  { id: GenreID.Comedy, name: 'Comedy' },
  { id: GenreID.Crime, name: 'Crime' },
  { id: GenreID.Documentary, name: 'Documentary' },
  { id: GenreID.Drama, name: 'Drama' },
  { id: GenreID.Family, name: 'Family' },
  { id: GenreID.Kids, name: 'Kids' },
  { id: GenreID.Mystery, name: 'Mystery' },
  { id: GenreID.News, name: 'News' },
  { id: GenreID.Reality, name: 'Reality' },
  { id: GenreID.SciFiFantasy, name: 'Sci-Fi & Fantasy' },
  { id: GenreID.Soap, name: 'Soap' },
  { id: GenreID.Talk, name: 'Talk' },
  { id: GenreID.WarPolitics, name: 'War & Politics' },
  { id: GenreID.Western, name: 'Western' },
];

// Priority Languages for Sorting
export const PRIORITY_LANGUAGES = ['en', 'ja', 'ko', 'es', 'fr', 'de'];

// Comprehensive List of Languages
export const ALL_LANGUAGES = [
  { code: '', name: 'All' },
  { code: 'en', name: 'English' },
  { code: 'ja', name: 'Japanese' },
  { code: 'ko', name: 'Korean' },
  { code: 'es', name: 'Spanish' },
  { code: 'fr', name: 'French' },
  { code: 'de', name: 'German' },
  { code: 'it', name: 'Italian' },
  { code: 'zh', name: 'Chinese' },
  { code: 'ru', name: 'Russian' },
  { code: 'pt', name: 'Portuguese' },
  { code: 'hi', name: 'Hindi' },
  { code: 'ar', name: 'Arabic' },
  { code: 'sv', name: 'Swedish' },
  { code: 'da', name: 'Danish' },
  { code: 'no', name: 'Norwegian' },
  { code: 'fi', name: 'Finnish' },
  { code: 'nl', name: 'Dutch' },
  { code: 'pl', name: 'Polish' },
  { code: 'tr', name: 'Turkish' },
  { code: 'th', name: 'Thai' },
  { code: 'id', name: 'Indonesian' },
  { code: 'vi', name: 'Vietnamese' },
  { code: 'cs', name: 'Czech' },
  { code: 'el', name: 'Greek' },
  { code: 'he', name: 'Hebrew' },
  { code: 'hu', name: 'Hungarian' },
  { code: 'ro', name: 'Romanian' },
  { code: 'sk', name: 'Slovak' },
  { code: 'uk', name: 'Ukrainian' },
  { code: 'bg', name: 'Bulgarian' },
  { code: 'hr', name: 'Croatian' },
  { code: 'sr', name: 'Serbian' },
  { code: 'sl', name: 'Slovenian' },
  { code: 'et', name: 'Estonian' },
  { code: 'lv', name: 'Latvian' },
  { code: 'lt', name: 'Lithuanian' },
  { code: 'fa', name: 'Persian' },
  { code: 'tl', name: 'Tagalog' },
  { code: 'ms', name: 'Malay' },
  { code: 'bn', name: 'Bengali' },
  { code: 'ta', name: 'Tamil' },
  { code: 'te', name: 'Telugu' },
  { code: 'ml', name: 'Malayalam' },
  { code: 'kn', name: 'Kannada' },
  { code: 'mr', name: 'Marathi' },
  { code: 'gu', name: 'Gujarati' },
  { code: 'ur', name: 'Urdu' },
  { code: 'sw', name: 'Swahili' },
  { code: 'is', name: 'Icelandic' },
  { code: 'ga', name: 'Irish' },
  { code: 'af', name: 'Afrikaans' },
  { code: 'sq', name: 'Albanian' },
  { code: 'hy', name: 'Armenian' },
  { code: 'az', name: 'Azerbaijani' },
  { code: 'eu', name: 'Basque' },
  { code: 'be', name: 'Belarusian' },
  { code: 'bs', name: 'Bosnian' },
  { code: 'ca', name: 'Catalan' },
  { code: 'cy', name: 'Welsh' },
  { code: 'eo', name: 'Esperanto' },
  { code: 'gl', name: 'Galician' },
  { code: 'ka', name: 'Georgian' },
  { code: 'ht', name: 'Haitian Creole' },
  { code: 'la', name: 'Latin' },
  { code: 'lb', name: 'Luxembourgish' },
  { code: 'mk', name: 'Macedonian' },
  { code: 'mn', name: 'Mongolian' },
  { code: 'ne', name: 'Nepali' },
];